from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('', views.dashboard, name='dashboard'),
    path('customers/', views.customers_list, name='customers_list'),
    path('customers/create/', views.customer_create, name='customer_create'),
    path('customers/<int:pk>/edit/', views.customer_edit, name='customer_edit'),
    path('customers/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('vehicles/', views.vehicles_list, name='vehicles_list'),
    path('vehicles/create/', views.vehicle_create, name='vehicle_create'),
    path('vehicles/<int:pk>/edit/', views.vehicle_edit, name='vehicle_edit'),
    path('vehicles/<int:pk>/delete/', views.vehicle_delete, name='vehicle_delete'),
    path('mechanics/', views.mechanics_list, name='mechanics_list'),
    path('mechanics/create/', views.mechanic_create, name='mechanic_create'),
    path('mechanics/<int:pk>/edit/', views.mechanic_edit, name='mechanic_edit'),
    path('mechanics/<int:pk>/delete/', views.mechanic_delete, name='mechanic_delete'),
    path('services/', views.services_list, name='services_list'),
    path('services/create/', views.service_create, name='service_create'),
    path('services/<int:pk>/edit/', views.service_edit, name='service_edit'),
    path('services/<int:pk>/delete/', views.service_delete, name='service_delete'),
    path('spareparts/', views.spareparts_list, name='spareparts_list'),
    path('spareparts/create/', views.sparepart_create, name='sparepart_create'),
    path('spareparts/<int:pk>/edit/', views.sparepart_edit, name='sparepart_edit'),
    path('spareparts/<int:pk>/delete/', views.sparepart_delete, name='sparepart_delete'),
    path('appointments/', views.appointments_list, name='appointments_list'),
    path('appointments/create/', views.appointment_create, name='appointment_create'),
    path('appointments/<int:pk>/edit/', views.appointment_edit, name='appointment_edit'),
    path('appointments/<int:pk>/delete/', views.appointment_delete, name='appointment_delete'),
    path('appointments/<int:pk>/cancel/', views.appointment_cancel, name='appointment_cancel'),
    path('insurances/', views.insurances_list, name='insurances_list'),
    path('insurances/create/', views.insurance_create, name='insurance_create'),
    path('insurances/<int:pk>/edit/', views.insurance_edit, name='insurance_edit'),
    path('insurances/<int:pk>/delete/', views.insurance_delete, name='insurance_delete'),
    path('workorders/', views.workorders_list, name='workorders_list'),
    path('workorders/create/', views.workorder_create, name='workorder_create'),
    path('workorders/<int:pk>/edit/', views.workorder_edit, name='workorder_edit'),
    path('workorders/<int:pk>/delete/', views.workorder_delete, name='workorder_delete'),
    path('workorders/<int:pk>/status/', views.workorder_status, name='workorder_status'),
    path('invoices/', views.invoices_list, name='invoices_list'),
    path('invoices/create/', views.invoice_create, name='invoice_create'),
    path('invoices/<int:pk>/edit/', views.invoice_edit, name='invoice_edit'),
    path('invoices/<int:pk>/delete/', views.invoice_delete, name='invoice_delete'),
    path('invoices/<int:pk>/detalle/', views.invoice_detail, name='invoice_detail'),
    path('invoices/<int:pk>/pdf/', views.invoice_pdf, name='invoice_pdf'),
    path('payments/', views.payments_list, name='payments_list'),
    path('payments/create/', views.payment_create, name='payment_create'),
    path('payments/<int:pk>/edit/', views.payment_edit, name='payment_edit'),
    path('payments/<int:pk>/delete/', views.payment_delete, name='payment_delete'),
    path('payments/<int:pk>/confirm/', views.payment_confirm, name='payment_confirm'),
    path('api/buscar-placa/', views.buscar_por_placa, name='buscar_por_placa'),
    path('api/orden/<int:pk>/', views.api_orden_detalle, name='api_orden_detalle'),
]
